### ISSUE TITLE
Updates to classes not loading unless you refresh the page

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [antfu/vite-plugin-windicss#1]
Updates to classes not loading unless you refresh the page.

Is this by design?

**Comment by antfu** [comment]
Can you share a repro?

**Comment by CharlesOkwuagwu** [comment]
https://github.com/CharlesOkwuagwu/vite-demo

**Comment by antfu** [comment]
@CharlesOkwuagwu Just did a few changes, can you bump to 0.0.6 and test out first? I will look into it if it still doesn't work.

**Comment by CharlesOkwuagwu** [comment]
> @CharlesOkwuagwu Just did a few changes, can you bump to 0.0.6 and test out first? I will look into it if it still doesn't work.

I will try it out.

**Comment by CharlesOkwuagwu** [comment]
> @CharlesOkwuagwu Just did a few changes, can you bump to 0.0.6 and test out first? I will look into it if it still doesn't work.

Hi it is still the same.

**Comment by antfu** [comment]
Are you using Windows?

**Comment by CharlesOkwuagwu** [comment]
yes, Windows 10

**Comment by JohnCampionJr** [comment]
This does seem to work now with the very latest commits.   

Also, can I say how cool this is?   Every time I started up vitesse,. it was like is there any way to avoid this build time and then this pops up :)

**Comment by CharlesOkwuagwu** [comment]
OK cool! Changes to `class` show up immediately now in the `.vue `files.

However changes to `class` on body in index.html still need a full page refresh.

**Comment by antfu** [comment]
@CharlesOkwuagwu I didn't implement the hmr for index.html as I thought it would trigger full refresh anyway. Is it longer a case in the latest vite?

**Comment by CharlesOkwuagwu** [comment]
@antfu This is fine the way it is! Changes to class show up as expected in .vue files.
A refresh for index.html is fine!
